apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-jenkins-ci
  labels:
    app: jenkins
spec:
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata: 
      name: create-container
      labels:
        app: jenkins
    spec:
      containers:
      - name: tomcat-image
        image: dogra21703/java_code:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name:  react-service
spec:
  selector:
    app:  jenkins
  type:  LoadBalancer 
  ports:
  - name:  tomcat-port
    port:  80
    targetPort:  8080